### ISSUE TITLE
TypeError after updating to 2.0.0

### ISSUE THREAD

**Issue by bkuri** [webpack-contrib/coffee-loader#79]
- Operating System: `5.10.7-3-MANJARO #1 SMP PREEMPT Fri Jan 15 21:11:34 UTC 2021 x86_64 GNU/Linux`
- Node Version: `14.15.3`
- NPM Version: `6.14.9`
- webpack Version: `4.46.0`
- coffee-loader Version: `2.0.0`

### Expected Behavior

Coffeescript files should be loaded/rendered correctly after upgrading to `v2.0.0`.

### Actual Behavior

I get the following error when loading instead:

```
Module build failed (from ./node_modules/coffee-loader/dist/cjs.js):                                        friendly-errors 14:36:03
TypeError: this.getOptions is not a function
    at Object.loader (/.../node_modules/coffee-loader/dist/index.js:21:24)
```

### Code

```js

// nuxt.config.js

export default {
  build: {
    extend ({ module }) {
      module.rules.push({
        exclude: /(node_modules)/,
        loader: 'coffee-loader',
        test: /\.coffee$/
      })
    }
  }
}
```

### How Do We Reproduce?

Simply upgrading to `2.0.0` gives me the error. I didn't change anything regarding webpack config or anything else.

**Comment by bkuri** [comment]
Sorry for the noise; just noticed the minimum webpack version is 5. Cheers.
